gillsdk/gill

.changeset/small-falcons-brake.md, packages/gill/src/__typetests__/transactions.ts, packages/gill/src/core/transactions.ts, packages/gill/src/types/index.ts, packages/gill/src/types/transactions.ts
`createTransaction` has insufficient types due to lack of overloads
made the `createTransaction` functions have proper types for all the conditions
=> [fix] createTransaction

.changeset/perfect-ravens-own.md, README.md, packages/gill/README.md, packages/gill/package.json, packages/gill/src/programs/token.ts, packages/gill/src/programs/token22.ts, packages/gill/tsup.config.package.ts, pnpm-lock.yaml
Add the token and token22 clients via a reexport under a `gill/system` subpath (due to naming collisions)
=> feat: token clients

.changeset/dull-deers-jam.md, README.md, packages/gill/README.md, packages/gill/src/__tests__/explorer.ts, packages/gill/src/core/explorer.ts, packages/gill/src/types/explorer.ts
- make `getExplorerUrl` return a string vice URL
- accept a signed transaction in addition to a transaction signature
=> get explorer url as string and signed transactions

.changeset/weak-yaks-joke.md, README.md, packages/gill/README.md, packages/gill/src/__tests__/explorer.ts, packages/gill/src/core/explorer.ts, packages/gill/src/types/explorer.ts
- improved the readme for explorer link and getting signatures
- simplified the `getExplorerLink` function to not accept a signed transaction (better tree shaking!)
=> refactor: explorer link

.changeset/green-rats-clap.md, packages/gill/src/__tests__/base64-transactions.ts, packages/gill/src/core/base64-transactions.ts, packages/gill/src/core/index.ts
added the `transactionToBase64` function to easily compile a transaction to a base64 string
=> feat: added base64 transaction helper

.changeset/silly-chicken-switch.md, README.md, packages/gill/README.md, packages/gill/src/__tests__/transactions.ts, packages/gill/src/__typetests__/transactions.ts, packages/gill/src/core/transactions.ts, packages/gill/src/programs/compute-budget.ts, packages/gill/src/types/transactions.ts
add support for setting the `computeUnitLimit` and `computeUnitPrice` instruction values inside of `createTransaction` to easily set them when creating transactions
=> setting compute budget in `createTransaction`

.changeset/fifty-ants-grow.md, packages/gill/src/__tests__/utils.ts, packages/gill/src/core/const.ts, packages/gill/src/core/index.ts, packages/gill/src/core/utils.ts
- added `GENESIS_HASH` constant with primary cluster hashes
- added `getMonikerFromGenesisHash` function
=> feat: genesis hash helpers

.changeset/nasty-dots-kiss.md, packages/gill/src/__tests__/explorer.ts, packages/gill/src/core/explorer.ts, packages/gill/src/types/explorer.ts
the `getExplorerLink` does not allow people to get a base explorer url
- allow output a cluster specific base urls
- added tests for this new output
=> `getExplorerLink` for base url

.changeset/thick-sheep-serve.md, packages/gill/src/__typetests__/prepare-transaction.ts, packages/gill/src/core/prepare-transaction.ts
the `prepareTransaction` function does not always return the correct type of "with blockhash"
- fixed return type, asserting it too
- added typechecks
=> fix: `prepareTransaction` return type

.changeset/big-mugs-push.md, examples/esrun/src/tokens.ts, packages/gill/src/__tests__/create-token-instructions.ts, packages/gill/src/__tests__/mint-tokens-instructions.ts, packages/gill/src/__typetests__/create-token-transaction.ts, packages/gill/src/__typetests__/mint-tokens-transaction.ts, packages/gill/src/programs/token/instructions/create-token.ts, packages/gill/src/programs/token/instructions/mint-tokens.ts, packages/gill/src/programs/token/instructions/types.ts, packages/gill/src/programs/token/transactions/create-token.ts, packages/gill/src/programs/token/transactions/mint-tokens.ts
- refactor common type info for token things
- renamed `payer` attribute to `feePayer` to keep consistent with transactions
=> refactor: type and name

.changeset/chilled-hornets-sniff.md, packages/gill/src/core/create-solana-client.ts, packages/gill/src/types/rpc.ts
The `createSolanaClient` function does not accept a port number for the rpc and rpcSubscriptions being created. And also does not change the port for localnet, which is different for the two connections.
- accept port number in config inputs
- special handle the default localnet port number
=> fix: create client port

.changeset/orange-cooks-dance.md, packages/gill/src/__tests__/create-token-instructions.ts, packages/gill/src/programs/token/instructions/create-token.ts
the mint token transaction builder does not correctly accept the user supplied token program
- add the token program address on the `getInitializeMintInstruction`
- added tests to cover the program address being set correctly
Fixes #45
=> fix: mint tokens program address

.changeset/nervous-rivers-move.md, packages/gill/src/kit/send-and-confirm-transaction.ts
allow `sendAndConfirmTransaction` to also handle signing
this way dev code no longer need to manually sign with `partiallySignTransactionMessageWithSigners` or `signTransactionMessageWithSigners` unless they want to
=> feat: sendAndConfirmTransaction handle signing

.changeset/hungry-ghosts-smash.md, README.md, packages/gill/README.md
create transaction example was provided twice.
remove duplicate
Fixes #
=> remove duplicate create tx example

.changeset/bright-moles-remain.md, packages/gill/src/core/create-solana-client.ts, packages/gill/src/types/rpc.ts, packages/react/src/types/providers.ts
=> refactor: client type names

.changeset/purple-moles-hear.md, package.json, packages/gill/package.json, pnpm-lock.yaml
the `@solana-program/*` packages (and potentially others) will attempt to resolve web3js v2 and/or kit, resulting in potential resolution issues between kit/web3js and gill
force override resolution to use gill where possible
=> forced resolution override for gill

.changeset/sour-kangaroos-peel.md, README.md, examples/get-started/src/intro.ts, packages/gill/README.md, packages/gill/src/__typetests__/create-solana-client.ts, packages/gill/src/__typetests__/simulate-transaction.ts, packages/gill/src/core/create-solana-client.ts, packages/gill/src/core/index.ts, packages/gill/src/core/simulate-transaction.ts, packages/gill/src/types/rpc.ts
simulating a transaction currently requires multiple steps and getting the correct info set. this can be simplified since it is such a common task
- add a simulate transaction factory
- include `simulateTransaction` in `createSolanaClient`
=> Simulate transaction factory

.changeset/brave-coins-dream.md, packages/gill/src/__tests__/rpc.ts, packages/gill/src/core/rpc.ts
`getPublicSolanaRpcUrl` does not accept `localhost` but it does accept `localnet` 
added localhost to `getPublicSolanaRpcUrl`
=> accept localhost in `getPublicSolanaRpcUrl`

.changeset/warm-humans-bow.md, packages/gill/src/__tests__/utils.ts, packages/gill/src/core/utils.ts
The current implementation of `lamportsToSol` can lose precision because of float division
`lamportsPerSol` now uses the scientific number format. The JS number formatter supports using this, eg. `format('500E-2') === 5`
So instead of dividing by `LAMPORTS_PER_SOL`, we just do `${lamports}E-9`. This works with a number or BigInt natively. 
This eliminates the cast to number, and the division, both of which can lose precision. It also generalises to arbitrary decimals if you want to provide a similar helper for tokens later. 
I've also added tests so you can verify this works!
=> Refactor lamportsPerSol to use scientific format

.changeset/long-dryers-exercise.md, packages/react/package.json
changeset peer dep updates results in major version bumps, including if using a workspace pacakge....
see [here](https://github.com/changesets/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies)
change `gill` to be a dep of `gill-react` instead of peer dep
=> changeset limitations for peer deps

.changeset/quick-pandas-bow.md, packages/gill/package.json, packages/gill/src/core/create-solana-client.ts
There was a bug in converting `https` urls into `wss` urls. The nature of the bug can be found by running
```
const thing= new URL("https://engine.mirror.ad/rpc/ac7e6cd2-8cee-455c-9b29-20e9424402f0")
console.log(thing.protocol)
```
You will find the url.protocol is `https:`
The existing code runs a function `.endsWith("s")` which the string ends with `:` not `s`. This push fixes that.
Fix the bug mentioned above
Fixes #
Fix the bug with converting https into wss
=> fix bug with https into ws

.changeset/selfish-dryers-burn.md, packages/react/src/hooks/balance.ts, packages/react/src/hooks/latest-blockhash.ts, packages/react/src/hooks/program-accounts.ts, packages/react/src/hooks/signature-statuses.ts, packages/react/src/hooks/types.ts
accept an abort signal for all the existing hooks as part of the standard gill rpc hook interface
=> feat: accept abort signal

.changeset/eleven-seas-love.md, packages/react/README.md, packages/react/src/__typeset__/account.ts, packages/react/src/hooks/account.ts
added `decoder` field for the `useAccount` hook to more easily use any `Decoder` for an account
=> [feat] useAccount decoder

.changeset/chilly-scissors-swim.md, packages/gill/src/__tests__/mint-tokens-instructions.ts, packages/gill/src/__tests__/transfer-tokens-instructions.ts, packages/gill/src/__typetests__/create-transaction.ts, packages/gill/src/core/create-transaction.ts, packages/gill/src/core/utils.ts, packages/gill/src/programs/token/addresses.ts, packages/gill/src/programs/token/instructions/create-token.ts, packages/gill/src/programs/token/instructions/mint-tokens.ts, packages/gill/src/programs/token/instructions/transfer-tokens.ts, packages/gill/src/programs/token/instructions/types.ts, packages/gill/src/programs/token/transactions/create-token.ts, packages/gill/src/programs/token/transactions/mint-tokens.ts, packages/gill/src/programs/token/transactions/transfer-tokens.ts, packages/gill/src/programs/token/transactions/types.ts
the transaction builders should accept an address or signer as the feePayer, but only actually accepts a `KeypairSigner`. making them really only usable in backend scripts that know the full keypair. not in frontend apps that use wallet ui to manage the user's secrey key
- update all the types for transaction builders to allow address or transaction signers
- when an address is supplied, it is auto upgraded to a `NoopSigner`
Fixes #98
=> [fix] transaction builders do not allow `Address` as `feePayer`

README.md, packages/gill/README.md
`bas58` text being used in README files where `base58` should be used instead.
`bas58` entries replaced with `base58`.
=> docs: fix 'bas58' typo in READMEs

.changeset/hot-lamps-scream.md, packages/gill/src/programs/token/instructions/create-token.ts
a type issue previously existed on the token22 package that required a `ts-ignore` comment. this is no longer required
removed 2 `ts-ignore` comments
=> chore: removed ts-ignore

packages/gill/src/programs/token/instructions/create-token.ts
The `getCreateTokenInstructions` function does not respect when `decimals` is `0` and will use the default value of `9`
Check if `args.decimals == null` as this will match both `null` and `undefined` but not zero
Fixes #112
=> Fix Default Decimals Logic to Respect Zero Value

.changeset/honest-kangaroos-glow.md, packages/gill/src/__tests__/create-token-instructions.ts
There is no test to ensure `decimals=0` will be correctly used when calling `getCreateTokenInstructions`
added a test
=> test: test the 0 decimals in `getCreateTokenInstructions`

.changeset/wicked-nails-clap.md, examples/get-started/README.md, examples/get-started/src/reference-keys.ts, packages/gill/src/__tests__/reference-keys.ts, packages/gill/src/core/index.ts, packages/gill/src/core/insert-reference-key.ts
It is cumbersome to manually insert reference keys into transactions, which is a common practice used by the Solana Pay and Blink spec
add helper functions to insert reference keys into transactions
=> [feat] add reference keys

.changeset/stale-panthers-fetch.md, packages/react/README.md, packages/react/src/__typeset__/token-account.ts, packages/react/src/hooks/index.ts, packages/react/src/hooks/token-account.ts
create `useTokenAccount` hook for fetching and decode associated token accounts
- Initializes creation of the hook
- If ATA not explicitly provided, derive based on mint, and owner's address
Fixes #93
=> feat: initialize token account hook for fetching ata info

.changeset/many-toys-visit.md, examples/get-started/package.json, packages/gill/package.json, pnpm-lock.yaml
update the @solana/kit and @solana-program/* deps
The updated version of kit (v2.1.1) gives us the benefit of [this PR](https://github.com/anza-xyz/kit/pull/473) that removed the branded types!
=> [chore] update deps

.changeset/friendly-chefs-serve.md, .github/workflows/publish-canary-releases.yml, e2e/imports/package.json, e2e/imports/src/imports.js, e2e/imports/src/imports.ts, packages/gill/generate-reexports.ts, packages/gill/src/programs/system/reexports.ts, packages/gill/src/programs/token-metadata/MAINTAINERS.md, packages/gill/src/programs/token-metadata/generated/types/mintArgs.ts
- canary publishing to only happy on canary tag, which now gets auto removed after canary is published
- renamed token metadata's `MintArgs` to `MetadataMintArgs` and documented in the maintainers.md file (which was also added)
- improved the reexport script to include types
=> refactor: rename mint args

.changeset/fair-carrots-brake.md, packages/gill/package.json
gill@0.10.0 broke program client imports and required a revert and new patch published. see https://github.com/solana-foundation/gill/pull/140
manually bump the gill version to continue publishing on 0.10.x
Fixes #139
=> chore: manual version

.github/workflows/publish-canary-releases.yml
the canary publishing is incorrectly attempting to run after merging to the master branch
prevent this. canary publishing should only be available on PRs
=> fix: no canary on master

.changeset/giant-lobsters-hope.md, packages/gill/src/__tests__/create-codama.config.ts, packages/gill/src/core/create-codama-config.ts, packages/gill/src/core/index.ts
Configuring [codama to work with gill](https://gill.site/docs/guides/codama) can by optimized if we use the `codama.js` instead of the json file with a helper function.
This PR implements the `createCodamaConfig` function.
```js
// codama.js
import { createCodamaConfig } from 'gill'
export default createCodamaConfig({
clientJs: 'anchor/src/client/js',
idl: 'anchor/target/idl/counter.json',
})
```
=> feat: add create-codama-config function

docs/content/docs/guides/codama.mdx
Currently Codama docs in Gill show only pnpm
adds other package managers or npx as the default for neutrality
Fixes #
=> fix: docs for multiple package manager in codama

.changeset/tough-plants-shop.md, packages/react/README.md, packages/react/src/__typeset__/signatures-for-address.ts, packages/react/src/hooks/index.ts, packages/react/src/hooks/signatures-for-address.ts
Implement getSignaturesforAddress RPC call as a hook
- implemented the hook: `useSignaturesForAddress` in `signatures-for-address.ts` file
- added typeset file for `signatures-for-address.ts`
- export the hook from main `index.ts`
- add example in docs
- followed existing naming convention and changeset rules for consistency
=> [react][feat] add useSignaturesForAddress hook

.changeset/violet-rivers-walk.md, packages/gill/src/__typetests__/create-transaction.ts, packages/gill/src/core/create-transaction.ts, packages/gill/src/types/transactions.ts
the `createTransaction` function required a `version` to be provided, where `legacy` is most commonly set anyway
- make `version` optional and default it to `legacy`
- added typesets to cover this
=> feat: make version optional

README.md, docs/content/docs/examples.mdx, docs/content/docs/meta.json, examples/get-started/README.md, package.json, packages/gill/README.md, packages/gill/package.json, packages/react/package.json, packages/svelte/package.json, packages/vue/package.json
- added the gill docs site as the `homepage` for the packages
- added an examples page to the docs
- sprinkled in some docs links into the core readme
Fixes: #181
=> homepage link and examples

docs/src/components/package-badges.tsx
While I was ~~stealing~~ borrowing code for the Wallet UI site I found this small nit.
Replaces the package name with a property that got passed in. 
Fixes #
=> fix: replace const with variable in PackageBadges

.changeset/itchy-dryers-laugh.md, .changeset/slow-ants-wash.md, packages/react/src/__typeset__/program-accounts.ts, packages/react/src/hooks/program-accounts.ts
as mentioned in issue #225 base58 encodings are deprecated by solana runtime so we need to remove them from the `useProgramAccounts` hook 
- removed the base58 encoding options from the `useProgramAccounts` hook 
- update the `program-accounts.ts` in `__typeset__` by removing the types related to base58
- updated the `.changeset` patch
=> Fix: remove base58 encoding from the useProgramAccounts hook

.changeset/wet-boats-talk.md, packages/gill/src/__tests__/base64-bytes-to.ts, packages/gill/src/core/base64-bytes-to.ts, packages/gill/src/core/index.ts
It can tedious to convert a base64 encoded byte array into valid and common formats, like `Address` and `Signature`. 
Note: This need is common when working with Solana Mobile's [Mobile Wallet Adapter library](https://github.com/solana-mobile/mobile-wallet-adapter) since base64 data is passed around
- added `base64BytesToAddress`, `base64BytesToSignature`, and `base64BytesToString` functions
- added tests for each
Fixes #
=> feat: "base64 bytes to X" functions

packages/gill/src/__tests__/create-codama.config.ts, packages/gill/src/core/create-codama-config.ts
`createCodamaConfig` fails when no `clientRust` argument is provided. In this case, the function inserts `rust: undefined` into the scripts object, which causes `codama run js` to throw:
```bash
✖ Cannot read properties of undefined (reading 'from')
```
This forces users to provide a `clientRust` path, even when they are only interested in generating JS clients.
```ts
...(clientRust && {
rust: {
from: "@codama/renderers-rust",
args: [
clientRust,
{
crateFolder: "clients/rust",
formatCode: true,
},
],
},
}),
```
**Explanation:**
If `clientRust` argument is provided, the rust config is included. 
If not, nothing is spread, meaning scripts contains only js.
This avoids `rust: undefined` in the object, which previously caused runtime errors.
Also updated tests to fit.
Fixes #207
=> fix:codama-client-generation

.changeset/cold-apes-work.md, packages/gill/src/core/create-solana-client.ts, packages/gill/src/types/rpc.ts, packages/react/src/hooks/account.ts, packages/react/src/hooks/balance.ts, packages/react/src/hooks/client.ts, packages/react/src/hooks/latest-blockhash.ts, packages/react/src/hooks/program-accounts.ts, packages/react/src/hooks/recent-prioritization-fees.ts, packages/react/src/hooks/signature-statuses.ts, packages/react/src/hooks/signatures-for-address.ts, packages/react/src/hooks/slot.ts, packages/react/src/hooks/token-account.ts, packages/react/src/hooks/token-mint.ts, packages/react/src/hooks/transaction.ts
There is a code comment in the `useUpdateSolanaClient` function.
```
/**
* todo: research more here
* removing queries here will force the cache to update automatically, but can result in the waterfall of data fetching
* but it seems that without it, the client side data does not auto refetch when the SolanaClient is changed :/
*/
```
The core issue was there is a race condition where the invalidation happens but it happens with the old client. If you ran it twice consecutively it would work. 
```
const localClient = createSolanaClient({
urlOrMoniker: 'http://127.0.0.1:8899',
})
updateClient(localClient)
setTimeout(() => {
updateClient(localClient)
}, 1)
```
The hooks have been updated to include the `urlOrMoniker ` as part of the `queryKey`. This means that you no longer need to …
=> fix: update solana client race condition
