gillsdk/gill

- packages/gill/src/__tests__/rpc.ts
- packages/gill/src/core/rpc.ts
- fix bug in `createSolanaClient` to allow custom urls
- fix bug in `getPublicSolanaRpcUrl` for testnet
- add tests for `getPublicSolanaRpcUrl`
> Rpc functions and tests

- .changeset/wise-wasps-lick.md
- packages/gill/src/core/index.ts
- packages/gill/src/core/transactions.ts
- packages/gill/src/types/transactions.ts
Added the `createTransaction` function to easily create Solana transactions
> feat: added createTransaction

- .changeset/flat-carrots-hang.md
- packages/gill/src/core/transactions.ts
- packages/gill/src/types/transactions.ts
Make the `latestBlockhash` in `createTransaction` optional
> refactor: optional blockhash

- .changeset/grumpy-lemons-crash.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- packages/gill/README.md
- add a readme to the core package and repo root
- update the pr template headings
> Add readme

- packages/gill/src/__tests__/transactions.ts
- packages/gill/src/core/transactions.ts
- packages/gill/src/types/index.ts
- fixed `createTransaction` for getting the correct `feePayer`
- added tests
> fix: createTransaction and tests

- .prettierignore
- packages/gill/package.json
- packages/gill/src/__tests__/kit/airdrop-internal-test.ts
- packages/gill/src/__tests__/kit/compute-limit-internal-test.ts
- packages/gill/src/__tests__/kit/decompile-transaction-message-fetching-lookup-tables-test.ts
- packages/gill/src/__tests__/kit/send-transaction-internal-test.ts
- packages/gill/src/__typetests__/kit/airdrop-typetests.ts
- packages/gill/src/__typetests__/kit/send-and-confirm-durable-nonce-transaction-typetests.ts
- packages/gill/src/__typetests__/kit/send-and-confirm-transaction-typetests.ts
- packages/gill/src/index.ts
- packages/gill/src/kit/airdrop-internal.ts
- packages/gill/src/kit/airdrop.ts
- packages/gill/src/kit/compute-limit-internal.ts
- packages/gill/src/kit/compute-limit.ts
- packages/gill/src/kit/decompile-transaction-message-fetching-lookup-tables.ts
- packages/gill/src/kit/index.ts
- packages/gill/src/kit/send-and-confirm-durable-nonce-transaction.ts
- packages/gill/src/kit/send-and-confirm-transaction.ts
- packages/gill/src/kit/send-transaction-internal.ts
- packages/gill/src/kit/send-transaction-without-confirming.ts
- packages/gill/src/programs/index.ts
- packages/gill/src/spl.ts
- packages/gill/src/types/global.d.ts
- packages/gill/tsup.config.package.ts
- pnpm-lock.yaml
> chore: kit

- .changeset/nasty-bats-taste.md
- packages/gill/src/__tests__/rpc.ts
- packages/gill/src/__typetests__/rpc.ts
- packages/gill/src/core/rpc.ts
- packages/gill/src/types/rpc.ts
> fix: client with correct types

- .changeset/blue-donkeys-listen.md
- packages/gill/src/__tests__/debug.ts
- packages/gill/src/core/debug.ts
- packages/gill/src/core/index.ts
- packages/gill/src/kit/send-transaction-internal.ts
added the `debug` logger and make it configurable from all environments
> feat: added debug logger

- .changeset/fuzzy-poems-fix.md
- README.md
- packages/gill/README.md
- packages/gill/package.json
- packages/gill/src/programs/index.ts
- pnpm-lock.yaml
- add the address lookup table program as a re-export
- fixed wording in readme about additional `solana-program` libraries
> [feat] add alt program

- .bundlemonrc.json
- .github/workflows/bundlesize.yml
- package.json
- pnpm-lock.yaml
added bundlemon to track bundle size changes
workflow copied from https://github.com/anza-xyz/solana-web3.js/blob/2d17620b60e47a3a09cf25a843416846e8a7c56f/.github/workflows/bundlesize.yml
> ci: bundlemon

- .changeset/selfish-pans-fold.md
- README.md
- packages/gill/README.md
- packages/gill/package.json
- document transaction builders in the readme
- link to the comparison scripts
> readme: document transaction builders

- packages/gill/src/programs/token/transactions/create-token.ts
- packages/gill/src/programs/token/transactions/mint-tokens.ts
- packages/gill/src/programs/token/transactions/types.ts
refactored the common types for transaction builders
> refactor: common types for token builders

- .changeset/silver-pumas-tickle.md
- packages/gill/src/core/utils.ts
added `lamportsToSol` function
> feat: added lamportsToSol

- .changeset/cuddly-taxis-search.md
- packages/build-scripts/dev-flag.ts
- packages/build-scripts/getBaseConfig.ts
- packages/gill/src/__tests__/base64-transactions.ts
- packages/gill/src/__tests__/create-token-instructions.ts
- packages/gill/src/__tests__/create-transaction.ts
- packages/gill/src/__tests__/explorer.ts
- packages/gill/src/core/create-solana-client.ts
- packages/gill/src/core/create-transaction.ts
- packages/gill/src/core/prepare-transaction.ts
- packages/gill/src/core/rpc.ts
- packages/gill/src/core/utils.ts
- packages/gill/src/kit/compute-limit-internal.ts
- packages/gill/src/kit/compute-limit.ts
- packages/gill/src/kit/decompile-transaction-message-fetching-lookup-tables.ts
- packages/gill/src/kit/send-and-confirm-durable-nonce-transaction.ts
- packages/gill/src/kit/send-and-confirm-transaction.ts
- packages/gill/src/kit/send-transaction-internal.ts
- packages/gill/src/kit/send-transaction-without-confirming.ts
- packages/gill/src/programs/compute-budget.ts
- packages/gill/src/programs/token-metadata/addresses.ts
- packages/gill/src/programs/token-metadata/generated/instructions/createMetadataAccountV3.ts
- packages/gill/src/programs/token-metadata/generated/types/useMethod.ts
- packages/gill/src/programs/token-metadata/generated/types/uses.ts
- packages/gill/src/programs/token/transactions/mint-tokens.ts
- packages/gill/src/types/transactions.ts
explicitly declare imports as types where possible
> refactor: type imports

- .changeset/grumpy-apricots-march.md
- packages/gill/src/__tests__/addresses.ts
- packages/gill/src/programs/token/addresses.ts
- added a parser for token program monikers
- added tests
> Token program monikers and parser

- .changeset/young-rocks-wait.md
- packages/gill/src/core/debug.ts
improved the docs on the debug globals
> docs: debug globals

- examples/get-started/src/airdrop.ts
SolAndy created a [video](https://www.youtube.com/watch?v=sApD4qNlMUg) on using `gill` and noticed some typos
fix typos!
> docs: typo

- .changeset/modern-oranges-tell.md
- packages/react/src/__typeset__/program-accounts.ts
- packages/react/src/__typeset__/signature-statuses.ts
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/program-accounts.ts
- packages/react/src/hooks/signature-statuses.ts
- packages/react/src/hooks/types.ts
- added the `useProgramAccounts` and `useSignatureStatuses` hooks
> added more hooks

- examples/tokens/.prettierrc
- examples/tokens/src/2.create-token-mint.ts
- examples/tokens/src/3.create-token-mint-builder.ts
- examples/tokens/src/6.transfer-tokens.ts
- examples/tokens/src/7.transfer-tokens-builder.ts
> refactor: token examples

- .changeset/bright-students-explode.md
- packages/react/README.md
- packages/react/src/__typeset__/account.ts
- packages/react/src/__typeset__/balance.ts
- packages/react/src/__typeset__/latest-blockhash.ts
- packages/react/src/hooks/account.ts
- packages/react/src/hooks/balance.ts
- packages/react/src/hooks/latest-blockhash.ts
the initial version of the hooks used a different interface api for inputs. we are making these standardize.
- updated the account, balance, and blockhash hooks to use the same standardized interface
- added typesets for the remaining hooks
> hooks refactor

- .changeset/tall-paws-clap.md
- packages/react/README.md
- packages/react/src/hooks/account.ts
- packages/react/src/hooks/balance.ts
- packages/react/src/hooks/latest-blockhash.ts
- packages/react/src/hooks/program-accounts.ts
- packages/react/src/hooks/signature-statuses.ts
added `useProgramAccounts` and `getSignatureStatuses` to the readme
> docs: readme for missing hooks

- .changeset/light-elephants-brake.md
- packages/gill/src/__tests__/get-oldest-signature.ts
- packages/gill/src/core/get-oldest-signature.ts
- packages/gill/src/core/index.ts
added the `getOldestSignatureForAddress` function
> feat: added get oldest signatures for address

- .changeset/dry-apricots-dream.md
- packages/gill/src/__tests__/ui-amount.ts
- packages/gill/src/programs/token/index.ts
- packages/gill/src/programs/token/ui-amount.ts
added `tokenUiAmountToAmount()` and `tokenAmountToUiAmount()` converters to convert to and from a token's "ui amount"
> feat: add token ui converters

- .github/workflows/publish-packages.yml
- .github/workflows/pull-requests.yml
unneeded workflows run for docs only changes.
add the docs ignore path
> ci: ignore docs

- docs/content/docs/guides/codama.mdx
people need docs or a guide on how to use the codama cli in order to create gill/kit compatible clients for their programs
added a codama guide for generating custom clients
Fixes #146 #41
> docs: codama guide

- docs/content/docs/compare/kit.mdx
- docs/content/docs/compare/meta.json
- docs/content/docs/meta.json
add a comparison doc for gill vs kit
> [docs] kit compare

- .changeset/config.json
- .changeset/perfect-keys-dream.md
- README.md
- docs/content/docs/compare/kit.mdx
- docs/content/docs/guides/codama.mdx
- docs/content/docs/guides/reference-keys.mdx
- docs/content/docs/index.mdx
- docs/content/docs/typescript.mdx
- docs/src/components/package-badges.tsx
- docs/src/const.ts
- examples/get-started/README.md
- package.json
- packages/build-scripts/CHANGELOG.md
- packages/gill/CHANGELOG.md
- packages/gill/README.md
- packages/gill/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/svelte/package.json
- packages/vue/package.json
the gill repo location changed
> chore: updated repo location

- .gitignore
- docs/package.json
- docs/pnpm-lock.yaml
- docs/src/app/layout.tsx
- docs/src/components/fathom-analytics.tsx
add fathom analytics (privacy focused analytics) to the docs site
https://usefathom.com
> [docs] add fathom analytics to the docs

- .changeset/config.json
- e2e/imports/package.json
- examples/get-started/package.json
- examples/get-started/tsconfig.json
- examples/tokens/package.json
- examples/tokens/tsconfig.json
the changesets were not properly configured in #215 
fix them
> fix: changeset

- .changeset/angry-comics-reflect.md
The PR #208 from @GuiBibeau was missing a changeset, so there was not a changelog entry created (or the Version PR being updated)
added the changeset to create the changelog entry
> chore: missing changeset

- docs/content/docs/guides/tokens/create-token.mdx
- docs/content/docs/meta.json
- docs/content/docs/react/examples.mdx
- docs/content/docs/react/getting-started.mdx
- docs/content/docs/react/hooks/client.mdx
- docs/content/docs/react/hooks/data-fetching.mdx
- docs/content/docs/react/hooks/index.mdx
- docs/content/docs/react/hooks/meta.json
- docs/content/docs/react/hooks/transactions.mdx
- docs/content/docs/react/index.mdx
- docs/content/docs/react/meta.json
- docs/generic.d.ts
- docs/src/app/api/search/route.ts
- docs/src/app/docs/[[...slug]]/page.tsx
- docs/src/lib/source.ts
- packages/react/README.md
- Fixed auto-generated cards issue in React documentation section
- Improved React Server Components explanation with clearer "use client" directive documentation
- Updated Node.js prerequisites to LTS v22 or later
- Hide auto-generated cards on React index page
- Add comprehensive explanation of "use client" directive and why it's needed
- Update framework references to be more specific (Next.js App Router, Remix, etc.)
- Enhance troubleshooting section with common RSC errors and solutions
- Update Node.js requirement to LTS v22 or later
> docs: improve React section documentation
